### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by Barbaross93** [phocus/gtk#5]
Hello,

I recently tried to install the AUR version of the package and I'm unable to install it receiving the following error message:
```
npm install && npm run build

> node-sass@4.12.0 install /home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/linux-x64-83_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.12.0 postinstall /home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.8.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /sbin/python
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /sbin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
gyp ERR! System Linux 5.8.1-arch1-1
gyp ERR! command "/usr/bin/node" "/home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/barbarossa/.cache/yay/phocus-gtk-theme-git/src/phocus-gtk-theme-git/node_modules/node-sass
gyp ERR! node -v v14.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/barbarossa/.npm/_logs/2020-08-15T14_05_15_631Z-debug.log
make: *** [Makefile:6: all] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
```
It looks like it might be a typo in the link for node-sass where it should be 72 rather than 83?

**Comment by Barbaross93** [comment]
Looks like it works now. Thanks!
